### PR TITLE
Bump `actions/checkout` and `actions/setup-python` actions to latest major

### PR DESCRIPTION
**Pull request by magnetikonline**
### What does this PR do?

Bumping `actions/checkout` and `actions/setup-python` actions to their latest major versions.

These both now support Node.js v16 - which is installed on GitHub Action cloud runners as v14 starts to fade away....

### Motivation

Quality of life update

### Testing Guidelines

Ran workflows.

### Additional Notes

N/A

### Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [x] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)
- [x] This PR passes the unit tests 
- [ ] This PR passes the installation tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Comment by magnetikonline** [comment]
ping @jvanbrie / @IvanTopolcic

**Comment by magnetikonline** [comment]
ping @tianchu

**Comment by magnetikonline** [comment]
hey @astuyve are you able to look at this?

**Review by astuyve — APPROVED** [review]

**Comment by astuyve** [comment]
Thanks for the PR @magnetikonline! Sorry for the delay

**Comment by magnetikonline** [comment]
Not a problem @astuyve, happy to contribute 👍

**Pull request merged**
