### PR TITLE
[aws] use the service from the dd_tags if it exists

### PR DESCRIPTION
**Pull request by guillaumelecerf**
### What does this PR do?

When we send ELB logs to Datadog, we end up having `source: elb` and `service: elb`, hence we cannot differentiate the logs from service X from those from service Y.

This PR changes the parsing so that if the tags contain `service:X`, it is used for DD_SERVICE.

### Motivation

Being able to filter the logs by service.

### Testing Guidelines

Tested by manually uploading the new code to our log forwarding AWS Lambda

### Types of changes

- [ ] Bug fix
- [X] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)
- [ ] This PR passes the unit tests 
- [ ] This PR passes the installation tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Comment by guillaumelecerf** [comment]
Superseded by #473

**Comment by guillaumelecerf** [comment]
@tianchu : is that PR ok for you?

**Comment by tianchu** [comment]
The changes look good to me, thanks for your contribution! 

I do want to make one clarification for other readers, with this change, now you can set the service tag using the `DdTags` option. However, because this option is at the forwarder level, so you would need to set up one forwarder per service.

**Review by tianchu — APPROVED** [review]

**Comment by guillaumelecerf** [comment]
Do you plan to create a release including this change plz?

**Pull request merged**
