### PR TITLE
Add VPC DNS Query logging from S3

### PR DESCRIPTION
**Pull request by rkitron**
Hi,

### What does this PR do?
Small change for handling VPC DNS Query logs stored in S3

### Additional Notes
This change works on my side

### Types of changes

- [ ] Bug fix
- [ X] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)
- [ ] This PR passes the unit tests 
- [ ] This PR passes the installation tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Comment by DylanLovesCoffee** [comment]
Thanks for contributing @benoitmenard! Looks great so far. Could you add a simple test case for S3 here? https://github.com/DataDog/datadog-serverless-functions/blob/8c2519b9d8b4cc5c5abafe99e86e72fda0a566d4/aws/logs_monitoring/tests/test_parsing.py#L171-L178

**Comment by agocs** [comment]
@benoitmenard Bump this issue. Do you think you can add a test case with an example DNS query?

**Comment by agocs** [comment]
SLS-1152

**Review by DylanLovesCoffee — APPROVED** [review]
LGTM 💯

**Pull request merged**
