### PR TITLE
support waf logs cloudwatch source with waf as service name

### PR DESCRIPTION
**Pull request by acloudsecure**
### What does this PR do?

support waf logs cloudwatch source with correct service name
### Motivation

AWS released support for logging WAF logs to cloudwatch sometime ago [here](https://aws.amazon.com/about-aws/whats-new/2021/12/awf-waf-cloudwatch-log-s3-bucket/)  but Datadog log forwarder sends service name as `cloudwatch` instead of `waf`. This PR fixes that.

### Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)
- [ ] This PR passes the unit tests 
- [ ] This PR passes the installation tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Review by sabiurr — APPROVED** [review]

**Comment by sabiurr** [comment]
nitpick: create a dict to have a mapping from log group prefix to source so we can replace these if statements with a dict lookup

**Comment by acloudsecure** [comment]
> nitpick: create a dict to have a mapping from log group prefix to source so we can replace these if statements with a dict lookup

I think its bit complicated so I am leaving it

**Review by sabiurr — APPROVED** [review]

**Comment by acloudsecure** [comment]
@buckhx and @cecileguyon can I get a review and tests to be run

**Comment by dnapbak** [comment]
Hi, it seems the feature is still not implemented. It would be useful to have that. Do you plan to merge the PR?

**Comment by billyshambrook** [comment]
This would be great to have especially as it looks like the AWS integration will soon autodiscover waf logs including from CloudWatch - https://github.com/DataDog/documentation/pull/21782

**Pull request closed without merging**
