### PR TITLE
Add s3 multipart upload lifecycle rule resolves #762

### LINKED ISSUE #762: AWS S3 Bucket lifecycle rule for aborted multipart uploads
**Describe what happened:**
1. It is considered best practice to configure S3 buckets with a lifecycle rule to abort multipart uploads that remain incomplete after 7 days. When you use the AWS SDK to upload a file to S3, if the file size exceeds a certain threshold (typically around 5 MB), the SDK will automatically initiate a multipart upload process behind the scenes. This process involves breaking the file into smaller parts and uploading them concurrently. Once all parts are uploaded, S3 combines them into a single object.
2. AWS Trusted advisor flags this with a warning. Adding this, would decrease noise for users and increase devops experience. I am not sure if only accounts with Enterprise Support get this specific warning, but i think everyone is affected. 

image

**Describe what you expected:**

1. Incomplete multipart uploads are cleaned up after a week. 
2. Trusted advisor warning disappears

**Steps to reproduce the issue:**

1. Go to the AWS Console
2. Open the "Trusted Advisor Service"
3. Go to "Cost optimization"
4. S3 Incomplete Multipart Upload Abort Configuration

### PR DESCRIPTION
**Pull request by xnick123**
Resolves #762

### What does this PR do?

Adds a s3 bucket lifecycle rule which deletes incomplete multiparts after 7 days. 

### Motivation

Reduce noise in AWS Trusted advisor, flagging this as a warning. 

### Testing Guidelines

Test if s3 bucket builds correctly (it worked for me manually)

### Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)
- [ ] This PR passes the unit tests 
- [ ] This PR passes the installation tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Comment by ge0Aja** [comment]
Hello @xnick123 
Thanks for the PR, could you rebase your change to include the latest updates on the lambda CFT ?
I'll validate the PR once you have it rebased. 
Thanks

**Comment by xnick123** [comment]
Hi @ge0Aja , great thank you. I just rebased, please let me know if something is not right.

**Comment by ge0Aja** [comment]
> Hi @ge0Aja , great thank you. I just rebased, please let me know if something is not right.

Looks like there's a glitch in the rebase, you've included previously merged commits. 
Could you reset HEAD to origin and rebase ? 
I'll download the template once rebased and test it out on our side.
Thanks

**Comment by xnick123** [comment]
Hi @ge0Aja my apologies, i have some knwoledge gaps. I opened a new [PR](https://github.com/DataDog/datadog-serverless-functions/pull/776) and linked that one to my issue. I hope i got it right this time.

**Pull request closed without merging**
