### PR TITLE
Add memorysize tag to enhanced lambda metrics

### PR DESCRIPTION
**Pull request by jcstorms1**
### What does this PR do?

Adds memorysize tag to aws enhanced lambda metrics

### CODE REVIEW

**Review by DarcyRaynerDD — APPROVED** [review]
LGTM

**Comment by tianchu** [comment]
Can you keep the original PR checklist/template?

**Comment by tianchu** [comment]
Do we have an integration test for enhanced metrics and tags that needs to be updated?

**Comment by jcstorms1** [comment]
I'll keep the template and yes it was tested with integration tests while debug logs were enabled.

**Pull request merged**
