### PR TITLE
added another check for gzip files

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

We have some log files in our S3 bucket that are gzipped but do not contain the gzip extension. This is also true of files that are sent from CloudWatch to Kinesis to S3. I would appreciate you considering to merge this for these type of files.

### Motivation

We want to invoke the datadog_lambda_collection function solely from an S3 bucket that collects all of our AWS logs.

### Additional Notes

Please ask if you have questions about how we have AWS & Datadog setup.

### CODE REVIEW

**Comment by tianchu** [comment]
Hi @shicholas, thanks for your PR! Looks good to me! Do you mind adding a comment with a link to the reference of the magic number? Also I assume you have tested this change and it worked in your setup, but can you confirm? Thank you!

**Comment by ghost** [comment]
Here is a link with the `magic header`, the two binary numbers referenced in this PR - http://www.onicos.com/staff/iz/formats/gzip.html

And yes, I can confirm this works in my setup.

**Comment by ghost** [comment]
hi @tianchu, is there anything else you'd like to see from me before deciding to accept/reject this PR? Thank you!

**Comment by tianchu** [comment]
@shicholas sorry the confusion and the late reply, my original ask was to add the link in the code as a comment :) I made the change directly, and thanks for your contribution!

**Pull request merged**
